#diccionario = {}
#k = 48
#for i in range(3):
#    diccionario[i] = k + 1 
#    k += 1 
#print(diccionario)





# -*- coding: utf-8 -*-
"""Reto4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDMCSm3l-Awp2FgXCwqJSfLBt4NCYbqv

#Dudas 22/06
"""

7 8
1 2 3 1 2 1 3 5 1

5 5 


5 3
1 1 1 1 2 1

4 4

5 3
1 2 4 3 2 1

2 1

p, q= input().split()
p = int(p)
q = int(q)
if p not in range(1, 1001):
  print('fuera de rango')
  if q<1 and q>1000:
    print('fuera de rango')
else:
  valores = input().split() 
  valores_int = []
  for i in valores:
    valores_int.append(int(i))
  print(valores)
  print(valores_int)

diccionario = {'a':[1, 3, 4,5], 'b':4, 'c':3}
print(diccionario)
diccionario['a'][1]

diccionario.get('a')[1]

diccionario = {'a':1, 'b':4, 'c':3}
diccionario['d'] = 45
print(diccionario)

diccionario['c'] = 48
print(diccionario)

diccionario = {}
k = 48
for i in range(3):
  diccionario[i] = k+1
  k +=1
print(diccionario)

lista = [34, 60, 40]
list(enumerate(lista))

diccionario = {}
lista = [34, 60, 40]
for i in range(len(lista)):
  diccionario[i] = lista[i]
print(diccionario)

diccionario = {}
lista = [34, 60, 40, 34]
for posicion, value  in enumerate(lista):
  diccionario[posicion] = value
print(diccionario)

diccionario = {}
lista = [34, 60, 40, 34]
for posicion, value  in enumerate(lista):
  diccionario[value] = posicion
print(diccionario)

#{}
#posicion=0, value=34, {34:0}
#posicion=1, value=60, {34:0, 60:1}
#posicion=2, value=40, {34:0, 60:1, 40:2}
#posicion=3, value=34, {34:3, 60:1, 40:2}

diccionario = {}
lista = [1, 2, 3, 4, 1, 2]
for posicion, value  in enumerate(lista):
  diccionario[value] = posicion
print(diccionario)
print(len(lista) - len(diccionario))

diccionario = {}
lista = [1, 1, 1, 1, 1, 1, 1]
copias_reales = 0
copias_m = 0
k = 2
for posicion, value  in enumerate(lista):
  if value in diccionario:
    copias_reales += 1
    if posicion - diccionario[value] <= k:
      copias_m += 1
  diccionario[value] = posicion
print(diccionario)
print(copias_reales)
print(copias_m)
#{}
#posicion=0, value=1, False, copias_reales=0, {1:0}, 
#posicion=1, value=2, False, copias_reales=0, {1:0, 2:1}
#posicion=2, value=3, False, copias_reales=0, {1:0, 2:1, 3:2}
#posicion=3, value=4, False, copias_reales=0, {1:0, 2:1, 3:2, 4:3}
#posicion=4, value=1, True, copias_reales=1, 4-0=4 <= 2 False, copias_m=0, {1:4, 2:1, 3:2, 4:3}
#posicion=5, value=2, True, copias_reales=2, 5-1=4 <= 2 False, copias_m=0, {1:4, 2:5, 3:2, 4:3}

diccionario = {}
lista = [1, 2, 3, 4, 1, 2]
copias_reales = 0
copias_m = 0
k = 2
for posicion, value  in enumerate(lista):
  if value in diccionario and posicion - diccionario[value] <= k:
    copias_m += 1
  diccionario[value] = posicion
copias_reales = len(lista)- len(diccionario)
print(diccionario)
print(copias_reales)
print(copias_m)

4 - 0 = 4
5 - 1 = 4
posicion_actual - posicion_anterior <= k

posicion - diccionario[value] <= k

lista = [1, 2, 3, 4, 1, 2]
for i in lista:
  print(i)

print(*lista, sep="\n")

help(print)

diccionario = {1: 4, 2: 5, 3: 2, 4: 3}
if 5 in diccionario:
  print('si está')
else:
  print('no está')