# -*- coding: utf-8 -*-
"""Reto_5_20_junio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dAqgohXIlbR9Lb7p1tPNUVcRdjZ2wN2k
"""

# Reto 5
def promedio_precios(tienda_ana):
  promedio=0
  for i in tienda_ana:  
    promedio+=tienda_ana[i][1]
  promedio/=len(tienda_ana) # promedio=promedio/len(tienda_ana)
  print(promedio)


def borrar_producto(tienda_ana,producto):
  if producto[0] in tienda_ana:
    tienda_ana.pop(producto[0]) # ['Melon',70,13]
    print(tienda_ana)
  else:
    print('ERROR')


def actualizar_producto(tienda_ana,producto):
  if producto[0] in tienda_ana:
    clave=producto[0] # [11,'Melon',70,13]
    #del producto[0]
    producto.pop(0) # ['Melon',70,13]
    tienda_ana[clave]= producto
    print(tienda_ana)
  else:
    print('ERROR')

def agregar_producto(tienda_ana,producto):
  if producto[0] in tienda_ana:
    print('ERROR')
  else:
    clave=producto[0]
    #del producto[0]
    producto.pop(0) # ['Melon',70,13]
    tienda_ana[clave]= producto
    print(tienda_ana)


def leer_datos():
  operacion= input() # AGREGAR ACTUALIZAR BORRAR
  producto=input().split() # [11,'Melon',70,13] =producto
  producto[0]= int(producto[0])
  producto[2]= float(producto[2])
  producto[3]= int(producto[3])
  return operacion, producto

def principal():
  tienda_ana={1:['Mango',7000.0,99],
              2:['Limones',3600.0,95],
              3:['Peras',2700.0,85],
              4:['Arandanos',8300.0,74],
              5:['Tomates',8400.0,44],
              6:['Fresas',7100.0,99],
              7:['Helado',4400.0,98],
              8:['Galletas',400.0,99],
              9:['Chocolates',4500.0,90],
              10:['Jamon',17000.0,89]}
  promedio_precios(tienda_ana)
  
  # operacion, producto=leer_datos()
  # if operacion=='AGREGAR':
  #   agregar_producto(tienda_ana,producto)
  # elif operacion=='ACTUALIZAR':
  #   actualizar_producto(tienda_ana,producto)
  # elif operacion=='BORRAR':
  #   borrar_producto(tienda_ana,producto)



principal()

tienda_ana={1:['Mango',7000.0,99],
              2:['Limones',3600.0,95],
              3:['Peras',2700.0,85],
              4:['Arandanos',8300.0,74],
              5:['Tomates',8100.0,44],
              6:['Fresas',7100.0,99],
              7:['Helado',4400.0,98],
              8:['Galletas',400.0,99],
              9:['Chocolates',4500.0,90],
              10:['Jamon',17000.0,89]}
promedio=0
for i in tienda_ana:  
  promedio+=tienda_ana[i][1]
promedio/=len(tienda_ana) # promedio=promedio/len(tienda_ana)
print(promedio)

# diccionario.keys() ---> clavesv [][]
# diccionario.values() ---> valores
# diccionario.items() ---> calves, valores